package com.firstrain.frapi.service.impl;

import static org.junit.Assert.assertEquals;

import com.diffblue.deeptestutils.Reflector;
import com.firstrain.frapi.events.IEvents;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.util.ArrayList;
import java.util.List;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ExpectedException;
import org.junit.rules.Timeout;

public class SingleCompanyEventsFilterDiffblueTest {

  @Rule public final ExpectedException thrown = ExpectedException.none();
  @Rule public final Timeout globalTimeout = new Timeout(10_000);

  /* testedClasses: SingleCompanyEventsFilter */
  // Test generated by Diffblue Deeptest.

  @Test
  public void ensureNullPropEventsInput0Output0() throws Exception {

    // Arrange
    final ArrayList<IEvents> filteredList = new ArrayList<IEvents>();

    // Act
    final Class<?> classUnderTest =
        Reflector.forName("com.firstrain.frapi.service.impl.SingleCompanyEventsFilter");
    final Method methodUnderTest =
        classUnderTest.getDeclaredMethod(
            "ensureNullPropEvents", Reflector.forName("java.util.List"));
    methodUnderTest.setAccessible(true);
    final List<IEvents> retval = (List<IEvents>) methodUnderTest.invoke(null, filteredList);

    // Assert
    final ArrayList<IEvents> arrayList = new ArrayList<IEvents>();
    assertEquals(arrayList, retval);
  }

  // Test generated by Diffblue Deeptest.

  @Test
  public void hasNullPropInputNullOutputNullPointerException() throws Throwable {

    // Arrange
    final IEvents event = null;

    // Act
    thrown.expect(NullPointerException.class);
    try {
      final Class<?> classUnderTest =
          Reflector.forName("com.firstrain.frapi.service.impl.SingleCompanyEventsFilter");
      final Method methodUnderTest =
          classUnderTest.getDeclaredMethod(
              "hasNullProp", Reflector.forName("com.firstrain.frapi.events.IEvents"));
      methodUnderTest.setAccessible(true);
      methodUnderTest.invoke(null, event);
    } catch (InvocationTargetException ex) {
      throw ex.getCause();
    }

    // Method is not expected to return due to exception thrown
  }
}
